---
sidebar: sidebar 
permalink: doc-gen-ai-assistant.html 
keywords: netapp, generative ai, doc 
summary: DOC 是我們在 docs.netapp.com 上的泛用 AI 輔助工具。DOC 旨在使用 NetApp .com 上發佈的內容來回應有關 NetApp 產品的問題。 
---
= NetApp 泛用 AI 型助理總覽
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
DOC 是我們在 docs.netapp.com 上的泛用 AI 輔助工具。DOC 旨在使用 NetApp .com 上發佈的內容來回應有關 NetApp 產品的問題。

DOC 可以根據先前的問題建立回應，提出其他問題，並說明如何產生回應。這使得它成為瀏覽 NetApp 文件的寶貴工具。



== 範圍和限制

Doc 只能回答基於 docs.netapp.com 上發布的內容的問題。

* Doc 僅根據產品最新發布的版本回答問題。例如，如果產品有 1.0 版和 2.0 版的文檔，Doc 僅參考最新的 2.0 版文檔。
* 為了獲得最佳效果，請務必使用特定的產品名稱。 Doc知道您提問時在哪個頁面，但這只是 Doc 在製定答案時考慮的幾個因素之一。
* DOC 可以使用 NetApp .com 支援的語言聊天，但未接受非英文版本的訓練。




== 寫下良好的提示

請遵循以下秘訣，以獲得 Doc.

提出具體問題。:: 寫下詳細問題，並指定產品名稱，版本和介面類型（ GUI ， API ）。例如：
+
--
[]
====
若要從 ONTAP 9.8 升級至 ONTAP 9.12.1 ，我應該在系統管理員中遵循哪些步驟？

====
--
要求步驟以完成工作。:: 要求 Doc 包含完成流程的步驟。不要問“如何在沒有互聯網的情況下安裝NetApp控制台代理？”，而是嘗試：
+
--
[]
====
在沒有網路的情況下安裝NetApp控制台代理程式應該遵循哪些步驟？

====
--
將複雜的問題分成多個區塊。:: 將複雜問題分成較小的問題（也稱為 _ 鏈接 _ ）。DOC 會記住先前的問題，並在您繼續聊天時建立更複雜的答案。
+
--
例如，不要詢問 Doc _如何在NetApp控制台中設定勒索軟體保護和備份計畫？ _ 而是嘗試：

[]
====
在NetApp控制台中配置勒索軟體保護的步驟是什麼？

====
接著詢問：

[]
====
在NetApp控制台中設定備份計畫的步驟是什麼？

====
--
請使用引號。:: 請將多字詞組括在引號中。這有助於 Doc 將該詞彙辨識為單一概念，就像您在與人對話時強調該詞彙的方式一樣。
+
--
例如，在本問題中， _ 如何在 ONTAP 中計算儲存效率？ _ 文件可能認為您提出的是 _ 儲存 _ 和 _ 效率 _ 兩個不相關的詞彙。請改為嘗試：

[]
====
如何在 ONTAP 中計算「儲存效率」？

====
--
檢視 Doc 的回應方式。:: 回應後、 Doc 會提供深入見解、讓您瞭解它如何產生回應。這可以讓您構思如何調整問題，以取得所需的結果。
清除聊天記錄:: 如果您想更改主題（例如，想詢問其他產品），請清除聊天記錄以開始新的會話。如果您在開始新主題之前沒有清除聊天記錄，可能會得到不準確的結果。




== 意見反應

我們正努力持續改善 Doc.請在 Doc 的聊天視窗中傳送意見給我們。請告訴我們、 Doc 的答案是否正確且有幫助、或是否不完整或有任何不足之處。如果您對文件的功能或回應有任何疑問或疑慮，也可以傳送電子郵件至 mailto ： ng-docComments @ NetApp 。 com[ 請與我們聯絡 ] 。
