---
sidebar: sidebar 
permalink: docs-netapp-com.html 
keywords:  
summary:  
---
= 關於 docs.netapp.com 網站
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


.網站導覽
video::77a636ba-4202-45bb-9e47-b08a01138502[panopto]
.交談記錄
[%collapsible]
====
0 ： 01:: 嗨、你好。這是 docs.netapp.com 團隊的 Ben 。在本影片中、我們將探討 docs.netapp.com 提供的功能和特色、協助您充分發揮內容觀賞體驗的效益。
0 ： 12:: 讓我們先來尋找您要尋找的內容。輸入文件網站之後、您可以使用網站左側進行瀏覽。
0 ： 20:: 如果文件有多個版本、您可以選取所使用產品版本的文件。
0 ： 28:: 使用搜尋方塊尋找文件網站中的內容。例如、我想要瞭解 Volume 加密的運作方式。
0 ： 36:: 如果您偏好瀏覽文件、可以使用目錄、它會組織成邏輯群組、例如「快速入門」和「使用產品」。
0 ： 45:: 如果您想要前往其他文件網站、可以使用麵包屑瀏覽 docs.netapp.com 。
0 ： 50:: 找到您要尋找的內容之後、就有幾項重要功能可協助您與內容互動。
0 ： 58:: 大多數的文件網站都有多種不同的語言版本、因此您可以以偏好的語言閱讀文件。
1:05:: 如果頁面有多個區段、您可以使用「在此頁面上」連結、直接前往您要尋找的內容。這些連結也能識別您在頁面上的位置、協助您在捲動時追蹤。
1:20:: 若要只專注於內容本身、您可以收合左右側邊欄。完成後、請將其展開以再次檢視導覽控制項。
1:33:: 如果您需要離線閱讀文件、您可以下載整個文件網站的 PDF 檔、或是網站內個別區段的 PDF 檔。
1 ： 41:: NetApp 文件是開放原始碼、旨在允許使用 GitHub 帳戶進行社群貢獻。提交您的意見回饋、要求文件更新或直接編輯內容、這些內容會在合併前提交給 NetApp 內容商機。
1 ： 59:: 在我們部分雲端服務的文件網站上、您可能會看到雲端供應商選項、可讓您將文件篩選至特定的雲端供應商。例如、如果您選取 Microsoft Azure 、則只會看到適用於 Azure 的內容。其他雲端供應商的內容不會出現。
2 ： 18:: 因為您可以從平板電腦、行動裝置或桌面存取我們的內容、所以我們使用回應性配置來確保我們的文件在任何裝置上看起來都很好。
2 時 28 分:: 就是這樣。我們希望您能喜歡使用這些功能、並感謝您成為我們內容社群的一份子。


====