---
jekyll: srd23-stable-12
settings:
  name: About docs.netapp.com
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: 關於網站
    url: "/docs-netapp-com.html"
  - title: 法律聲明
    url: "/legal-notices.html"
